name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: >
          mkdir release && cp -r ./source release/bob-popclip.popclipext
          && cd release && zip -r bob-popclip.popclipext.zip bob-popclip.popclipext
          && mv bob-popclip.popclipext.zip bob-popclip.popclipextz
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: release/bob-popclip.popclipextz
          asset_name: bob-popclip.popclipextz
          tag: ${{ github.ref }}
          overwrite: true
